version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "entrega-3-tg-1"
          ContainerPort: 8000
        PlatformVersion: "LATEST"
