version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install pytest pytest-flask pytest-mock

  pre_build:
    commands:
      - echo "Setting up environment..."
      - python --version
      - pip --version

  build:
    commands:
      - echo "Running unit tests..."
      - python -m pytest tests/ -v --tb=short
      - echo "Tests completed successfully"

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Creating deployment artifact..."
      - mkdir -p artifacts
      - cp -r . artifacts/
      - cd artifacts && zip -r ../blacklist-api-artifact.zip . -x "*.git*" "*__pycache__*" "*.pytest_cache*" "*tests*" "*.env*"

artifacts:
  files:
    - blacklist-api-artifact.zip
  discard-paths: yes

cache:
  paths:
    - "/root/.cache/pip"
